"""Database v2.0

Revision ID: 4d56622eaa34
Revises: 1028e2fa3a2c
Create Date: 2023-04-30 14:51:50.614337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d56622eaa34'
down_revision = '1028e2fa3a2c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TeamUsers',
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['Team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], )
    )
    op.add_column('Team', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Team', 'User', ['owner_id'], ['id'])
    op.drop_constraint('User_team_id_fkey', 'User', type_='foreignkey')
    op.drop_column('User', 'team_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('User_team_id_fkey', 'User', 'Team', ['team_id'], ['id'])
    op.drop_constraint(None, 'Team', type_='foreignkey')
    op.drop_column('Team', 'owner_id')
    op.drop_table('TeamUsers')
    # ### end Alembic commands ###
