"""Add Message Table

Revision ID: a146cd8ea47e
Revises: f6c6f95c2cc7
Create Date: 2023-07-10 18:09:34.612666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a146cd8ea47e'
down_revision = 'f6c6f95c2cc7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Message',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_type', sa.Enum('text', name='contenttypes'), nullable=False),
    sa.Column('text', sa.String(length=512), nullable=True),
    sa.Column('media', sa.String(length=128), nullable=True),
    sa.Column('is_reply', sa.Boolean(), nullable=False),
    sa.Column('reply_to', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['Game.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['Team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Message_id'), 'Message', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Message_id'), table_name='Message')
    op.drop_table('Message')
    # ### end Alembic commands ###
